In [2]:
##vous devez exécuter ces premières lignes de code pour récupérer votre série: il s'agit de simulation chacun d'entre vous aura donc une série différente !
set.seed(0912)
xsim <- arima.sim(model = list(ar = 0.3, ma = 0.6), n = 600)
xsim <- xsim + .02*seq(1,600)
x<-as.data.frame(xsim)

In [ ]:
x

    x
1   -0.2671877
2   -1.1401465
3    1.1428536
4    3.2225878
5    2.5695348
6    2.4818906
7    1.5109105
8    0.3527389
9    1.6332384
10   2.4466561
11   3.0942844
12   2.3645716
13   1.2152733
14   1.6709261
15   3.2395016
16   0.6647586
17  -1.4504582
18  -1.5758861
19  -1.0651267
20  -0.2883901
21   1.9113875
22   0.9303995
23   1.6232278
24   0.3154518
25  -0.9288307
26  -0.6408552
27   1.1625990
28   3.2344763
29   2.3649172
30   0.4623500
⋮   ⋮
571 12.738893
572 13.282267
573 12.566291
574 10.852196
575  9.291664
576  9.460221
577  9.477656
578 10.383539
579  8.703585
580  8.606437
581 11.545980
582 12.022765
583 12.186021
584 10.581629
585  8.144457
586 10.771973
587 12.158226
588 11.246058
589 10.101964
590  9.001960
591  9.510215
592 12.541738
593 12.017342
594 11.874668
595 10.103742
596  9.363874
597 10.864611
598 11.216808
599 10.208056
600 10.137084

In [1]:
x = ts(x, start=1970, frequency=12)

ERROR: Error in eval(expr, envir, enclos): object 'x' not found